# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Anish's Blog
email: anish.lnx@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<h3>Hello, world!</h3> home for my tech learnings & script snippets"

social_links:
  linkedin: "https://www.linkedin.com/in/anish-n-aa08a31/"
  github: "https://github.com/aanishn"

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aanishn.github.io/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

plugins:
 - jekyll-sitemap
 - jekyll-seo-tag
